-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 09:23:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `Nome_Equipe` VARCHAR(45) NOT NULL,
  `Qtd_Integrantes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SuperHeroi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SuperHeroi` (
  `idSuperHeroi` INT NOT NULL AUTO_INCREMENT,
  `Nome_heroi` VARCHAR(50) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idSuperHeroi`),
  INDEX `fk_SuperHeroi_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_SuperHeroi_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poderes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Poderes` (
  `idPoderes` INT NOT NULL AUTO_INCREMENT,
  `Poder` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPoderes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SuperHeroi_has_Poderes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SuperHeroi_has_Poderes` (
  `SuperHeroi_idSuperHeroi` INT NOT NULL,
  `Poderes_idPoderes` INT NOT NULL,
  PRIMARY KEY (`SuperHeroi_idSuperHeroi`, `Poderes_idPoderes`),
  INDEX `fk_SuperHeroi_has_Poderes_Poderes1_idx` (`Poderes_idPoderes` ASC) VISIBLE,
  INDEX `fk_SuperHeroi_has_Poderes_SuperHeroi_idx` (`SuperHeroi_idSuperHeroi` ASC) VISIBLE,
  CONSTRAINT `fk_SuperHeroi_has_Poderes_SuperHeroi`
    FOREIGN KEY (`SuperHeroi_idSuperHeroi`)
    REFERENCES `mydb`.`SuperHeroi` (`idSuperHeroi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SuperHeroi_has_Poderes_Poderes1`
    FOREIGN KEY (`Poderes_idPoderes`)
    REFERENCES `mydb`.`Poderes` (`idPoderes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Missao` (
  `idTipo_Missao` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Missao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Missao_equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Missao_equipe` (
  `idMissoes` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  `Equipe_idEquipe` INT NOT NULL,
  `Tipo_Missao_idTipo_Missao` INT NOT NULL,
  PRIMARY KEY (`idMissoes`),
  INDEX `fk_Missao_equipe_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  INDEX `fk_Missao_equipe_Tipo_Missao1_idx` (`Tipo_Missao_idTipo_Missao` ASC) VISIBLE,
  CONSTRAINT `fk_Missao_equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Missao_equipe_Tipo_Missao1`
    FOREIGN KEY (`Tipo_Missao_idTipo_Missao`)
    REFERENCES `mydb`.`Tipo_Missao` (`idTipo_Missao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Missao_Heroi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Missao_Heroi` (
  `idMissao_Heroi` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  `SuperHeroi_idSuperHeroi` INT NOT NULL,
  `Tipo_Missao_idTipo_Missao` INT NOT NULL,
  PRIMARY KEY (`idMissao_Heroi`),
  INDEX `fk_Missao_Heroi_SuperHeroi1_idx` (`SuperHeroi_idSuperHeroi` ASC) VISIBLE,
  INDEX `fk_Missao_Heroi_Tipo_Missao1_idx` (`Tipo_Missao_idTipo_Missao` ASC) VISIBLE,
  CONSTRAINT `fk_Missao_Heroi_SuperHeroi1`
    FOREIGN KEY (`SuperHeroi_idSuperHeroi`)
    REFERENCES `mydb`.`SuperHeroi` (`idSuperHeroi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Missao_Heroi_Tipo_Missao1`
    FOREIGN KEY (`Tipo_Missao_idTipo_Missao`)
    REFERENCES `mydb`.`Tipo_Missao` (`idTipo_Missao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fraquezas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fraquezas` (
  `idFraquezas` INT NOT NULL AUTO_INCREMENT,
  `Fraquezas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFraquezas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fraquezas_has_SuperHeroi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fraquezas_has_SuperHeroi` (
  `Fraquezas_idFraquezas` INT NOT NULL,
  `SuperHeroi_idSuperHeroi` INT NOT NULL,
  PRIMARY KEY (`Fraquezas_idFraquezas`, `SuperHeroi_idSuperHeroi`),
  INDEX `fk_Fraquezas_has_SuperHeroi_SuperHeroi1_idx` (`SuperHeroi_idSuperHeroi` ASC) VISIBLE,
  INDEX `fk_Fraquezas_has_SuperHeroi_Fraquezas1_idx` (`Fraquezas_idFraquezas` ASC) VISIBLE,
  CONSTRAINT `fk_Fraquezas_has_SuperHeroi_Fraquezas1`
    FOREIGN KEY (`Fraquezas_idFraquezas`)
    REFERENCES `mydb`.`Fraquezas` (`idFraquezas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fraquezas_has_SuperHeroi_SuperHeroi1`
    FOREIGN KEY (`SuperHeroi_idSuperHeroi`)
    REFERENCES `mydb`.`SuperHeroi` (`idSuperHeroi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `mydb`.`Equipe` (`Nome_Equipe`, `Qtd_Integrantes`) VALUES
('Liga da Justiça', '5'),
('Vingadores', '6'),
('X-Men', '7'),
('Guardiões da Galáxia', '5'),
('Defensores', '4'),
('Titãs', '6'),
('Fugitivos', '5'),
('Sociedade da Justiça', '8'),
('X-Force', '5'),
('Esquadrão Suicida', '6');

INSERT INTO `mydb`.`SuperHeroi` (`Nome_heroi`, `Descricao`, `Equipe_idEquipe`) VALUES
('Superman', 'O último filho de Krypton', 1),
('Homem de Ferro', 'Gênio, bilionário, playboy e filantropo', 2),
('Wolverine', 'Mutante com garras retráteis', 3),
('Senhor das Estrelas', 'Líder dos Guardiões da Galáxia', 4),
('Demolidor', 'Advogado cego e justiceiro', 5),
('Robin', 'Parceiro do Batman', 6),
('Fugitivo', 'Com poderes de velocidade', 7),
('Flash', 'Herói velocista', 8),
('Deadpool', 'O mercenário tagarela', 9),
('Arlequina', 'A rainha do crime', 10);

INSERT INTO `mydb`.`Poderes` (`Poder`) VALUES
('Voo'),
('Superforça'),
('Regeneração'),
('Controle Mental'),
('Invisibilidade'),
('Telecinese'),
('Teletransporte'),
('Telepatia'),
('Manipulação do Tempo'),
('Criação de Portais');



INSERT INTO `mydb`.`Tipo_Missao` (`Tipo`) VALUES
('Resgate'),
('Combate ao Crime'),
('Exploração'),
('Diplomacia'),
('Investigação'),
('Defesa Planetária'),
('Infiltração'),
('Captura de Vilão'),
('Proteção de Artefato'),
('Missão Secreta');

INSERT INTO `mydb`.`Missao_equipe` (`Descricao`, `Equipe_idEquipe`, `Tipo_Missao_idTipo_Missao`) VALUES
('Salvar civis de prédio em chamas', 1, 1),
('Impedir assalto a banco', 2, 2),
('Explorar novo planeta', 3, 3),
('Negociar paz entre nações', 4, 4),
('Investigar série de assassinatos', 5, 5),
('Defender Terra de invasão alienígena', 6, 6),
('Infiltrar base inimiga', 7, 7),
('Capturar vilão fugitivo', 8, 8),
('Proteger artefato místico', 9, 9),
('Executar missão ultra secreta', 10, 10);

INSERT INTO `mydb`.`Missao_Heroi` (`Descricao`, `SuperHeroi_idSuperHeroi`, `Tipo_Missao_idTipo_Missao`) VALUES
('Resgatar reféns', 1, 1),
('Combater gangue nas ruas', 2, 2),
('Explorar dimensão alternativa', 3, 3),
('Negociar paz como embaixador', 4, 4),
('Investigar desaparecimentos', 5, 5),
('Defender contra invasores cósmicos', 6, 6),
('Infiltrar organização criminosa', 7, 7),
('Capturar criminoso procurado', 8, 8),
('Proteger artefato mágico', 9, 9),
('Executar missão secreta', 10, 10);

INSERT INTO `mydb`.`Fraquezas` (`Fraquezas`) VALUES
('Kryptonita'),
('Sem armadura'),
('Adamantium'),
('Resistência psíquica'),
('Campo de força invisível'),
('Contra-ataque telecinético'),
('Interferência dimensional'),
('Bloqueio telepático'),
('Manipulação temporal'),
('Inabilidade de seguir regras');

INSERT INTO `mydb`.`Fraquezas_has_SuperHeroi` (`Fraquezas_idFraquezas`, `SuperHeroi_idSuperHeroi`) VALUES
(1, 2),
(2, 3),
(3, 4),
(4, 5),
(5, 4),
(6, 9),
(7, 4),
(8, 2),
(9, 1),
(10, 1);


INSERT INTO `mydb`.`SuperHeroi_has_Poderes` (`SuperHeroi_idSuperHeroi`, `Poderes_idPoderes`) VALUES
(1, 9),
(2, 6),
(3, 5),
(4, 2),
(5, 2),
(6, 4),
(7, 3),
(8, 4),
(9, 8),
(10, 1);

select * from superheroi_has_poderes;



