-- MySQL Script generated by MySQL Workbench
-- Wed Nov 22 08:49:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema seresVivos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seresVivos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seresVivos` DEFAULT CHARACTER SET utf8 ;
USE `seresVivos` ;

-- -----------------------------------------------------
-- Table `seresVivos`.`Reino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Reino` (
  `idReino` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Filo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Filo` (
  `idFilo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `FK_Reino_idReino` INT NOT NULL,
  PRIMARY KEY (`idFilo`),
  INDEX `fk_Filo_Reino_idx` (`FK_Reino_idReino` ASC) VISIBLE,
  CONSTRAINT `fk_Filo_Reino`
    FOREIGN KEY (`FK_Reino_idReino`)
    REFERENCES `seresVivos`.`Reino` (`idReino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Classe` (
  `idclasse` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `FK_Filo_idFilo` INT NOT NULL,
  PRIMARY KEY (`idclasse`),
  INDEX `fk_Classe_Filo1_idx` (`FK_Filo_idFilo` ASC) VISIBLE,
  CONSTRAINT `fk_Classe_Filo1`
    FOREIGN KEY (`FK_Filo_idFilo`)
    REFERENCES `seresVivos`.`Filo` (`idFilo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Ordem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Ordem` (
  `idordem` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `FK_Classe_idclasse` INT NOT NULL,
  PRIMARY KEY (`idordem`),
  INDEX `fk_ordem_Classe1_idx` (`FK_Classe_idclasse` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_Classe1`
    FOREIGN KEY (`FK_Classe_idclasse`)
    REFERENCES `seresVivos`.`Classe` (`idclasse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Familia` (
  `idFamilia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `FK_ordem_idordem` INT NOT NULL,
  PRIMARY KEY (`idFamilia`),
  INDEX `fk_Familia_ordem1_idx` (`FK_ordem_idordem` ASC) VISIBLE,
  CONSTRAINT `fk_Familia_ordem1`
    FOREIGN KEY (`FK_ordem_idordem`)
    REFERENCES `seresVivos`.`Ordem` (`idordem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `origem_geografica` VARCHAR(45) NOT NULL,
  `FK_Familia_idFamilia` INT NOT NULL,
  PRIMARY KEY (`idgenero`),
  INDEX `fk_Genero_Familia1_idx` (`FK_Familia_idFamilia` ASC) VISIBLE,
  CONSTRAINT `fk_Genero_Familia1`
    FOREIGN KEY (`FK_Familia_idFamilia`)
    REFERENCES `seresVivos`.`Familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Especie` (
  `idEspecie` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `populacao` BIGINT NOT NULL,
  `FK_Genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`idEspecie`),
  INDEX `fk_Especie_Genero1_idx` (`FK_Genero_idgenero` ASC) VISIBLE,
  CONSTRAINT `fk_Especie_Genero1`
    FOREIGN KEY (`FK_Genero_idgenero`)
    REFERENCES `seresVivos`.`Genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Habitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Habitat` (
  `idHabitat` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `tipo_terreno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHabitat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`PadraoReproducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`PadraoReproducao` (
  `idPadraoReproducao` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPadraoReproducao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Alimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Alimentacao` (
  `idAlimentacao` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlimentacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `FK_Especie_idEspecie` INT NOT NULL,
  `FK_Habitat_idHabitat` INT NOT NULL,
  `FK_PadraoReproducao_idPadraoReproducao` INT NOT NULL,
  `FK_Alimentacao_idAlimentacao` INT NOT NULL,
  PRIMARY KEY (`idAnimal`),
  INDEX `fk_Animal_Especie1_idx` (`FK_Especie_idEspecie` ASC) VISIBLE,
  INDEX `fk_Animal_Habitat1_idx` (`FK_Habitat_idHabitat` ASC) VISIBLE,
  INDEX `fk_Animal_PadraoReproducao1_idx` (`FK_PadraoReproducao_idPadraoReproducao` ASC) VISIBLE,
  INDEX `fk_Animal_Alimentacao1_idx` (`FK_Alimentacao_idAlimentacao` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_Especie1`
    FOREIGN KEY (`FK_Especie_idEspecie`)
    REFERENCES `seresVivos`.`Especie` (`idEspecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Habitat1`
    FOREIGN KEY (`FK_Habitat_idHabitat`)
    REFERENCES `seresVivos`.`Habitat` (`idHabitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_PadraoReproducao1`
    FOREIGN KEY (`FK_PadraoReproducao_idPadraoReproducao`)
    REFERENCES `seresVivos`.`PadraoReproducao` (`idPadraoReproducao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Alimentacao1`
    FOREIGN KEY (`FK_Alimentacao_idAlimentacao`)
    REFERENCES `seresVivos`.`Alimentacao` (`idAlimentacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`DoencasTransmissiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`DoencasTransmissiveis` (
  `idDoencasTransmissiveis` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDoencasTransmissiveis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seresVivos`.`Animal_has_DoencasTransmissiveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seresVivos`.`Animal_has_DoencasTransmissiveis` (
  `Animal_idAnimal` INT NOT NULL AUTO_INCREMENT,
  `DoencasTransmissiveis_idDoencasTransmissiveis` INT NOT NULL,
  PRIMARY KEY (`Animal_idAnimal`, `DoencasTransmissiveis_idDoencasTransmissiveis`),
  INDEX `fk_Animal_has_DoencasTransmissiveis_DoencasTransmissiveis1_idx` (`DoencasTransmissiveis_idDoencasTransmissiveis` ASC) VISIBLE,
  INDEX `fk_Animal_has_DoencasTransmissiveis_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_has_DoencasTransmissiveis_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `seresVivos`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_has_DoencasTransmissiveis_DoencasTransmissiveis1`
    FOREIGN KEY (`DoencasTransmissiveis_idDoencasTransmissiveis`)
    REFERENCES `seresVivos`.`DoencasTransmissiveis` (`idDoencasTransmissiveis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
