-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 08:30:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurante` DEFAULT CHARACTER SET utf8 ;
USE `restaurante` ;

-- -----------------------------------------------------
-- Table `restaurante`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`produto` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurante`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurante`.`pedido` ;

CREATE TABLE IF NOT EXISTS `restaurante`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `FK_produto_idproduto` INT NOT NULL,
  `mesa` INT NOT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_produto_idx` (`FK_produto_idproduto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_produto`
    FOREIGN KEY (`FK_produto_idproduto`)
    REFERENCES `restaurante`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
