-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 10:30:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mae` (
  `idmae` INT NOT NULL AUTO_INCREMENT,
  `nome_mae` VARCHAR(90) NOT NULL,
  `idade` INT NOT NULL,
  PRIMARY KEY (`idmae`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filho` (
  `idfilho` INT NOT NULL AUTO_INCREMENT,
  `nome_filho` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `FK_idmae` INT NOT NULL,
  PRIMARY KEY (`idfilho`),
  INDEX `fk_filho_mae_idx` (`FK_idmae` ASC) VISIBLE,
  CONSTRAINT `fk_filho_mae`
    FOREIGN KEY (`FK_idmae`)
    REFERENCES `mydb`.`mae` (`idmae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nome_paciente` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `CPF` BIGINT NOT NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` BIGINT NOT NULL,
  `CRM` VARCHAR(45) NOT NULL,
  `Especializacao` VARCHAR(45) NOT NULL,
  `medicocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `FK_paciente_idpaciente` INT NOT NULL,
  `FK_medico_idmedico` INT NOT NULL,
  `idconsulta` INT NOT NULL,
  `consultorio` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `detalhes` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consulta_paciente1_idx` (`FK_paciente_idpaciente` ASC) VISIBLE,
  INDEX `fk_consulta_medico1_idx` (`FK_medico_idmedico` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`FK_paciente_idpaciente`)
    REFERENCES `mydb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_medico1`
    FOREIGN KEY (`FK_medico_idmedico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `idLivro` INT NOT NULL AUTO_INCREMENT,
  `nome_livro` VARCHAR(45) NOT NULL,
  `ano_lancamento` YEAR NOT NULL,
  `cod_barras` BIGINT NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `num_cartao` BIGINT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `FK_Livro_idLivro` INT NOT NULL,
  `FK_Cliente_idCliente` INT NOT NULL,
  `data_devolucao` DATE NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_emprestimo_Livro1_idx` (`FK_Livro_idLivro` ASC) VISIBLE,
  INDEX `fk_emprestimo_Cliente1_idx` (`FK_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_Livro1`
    FOREIGN KEY (`FK_Livro_idLivro`)
    REFERENCES `mydb`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_Cliente1`
    FOREIGN KEY (`FK_Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
